source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '14.2'

use_frameworks!
workspace 'TrendingGifs'

target 'Application' do
  project 'Application/Application'
  # Pods for Application

end

target 'Networking' do
  project 'Networking/Networking'
  # Pods for Networking
  pod 'RxSwift'

end